# Generated by Django 5.0.7 on 2024-07-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arma',
            old_name='poder',
            new_name='nivel',
        ),
    ]
