# Generated by Django 5.0.7 on 2024-07-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0002_rename_poder_arma_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='elemento',
            field=models.CharField(choices=[('eletrico', 'Elétrico'), ('fogo', 'Fogo'), ('agua', 'Água'), ('sombrio', 'Sombrio'), ('neutro', 'Neutro'), ('solar', 'Solar')], default='neutro', max_length=10),
        ),
    ]
