# Generated by Django 5.0.7 on 2024-07-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arma', '0003_arma_elemento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arma',
            name='tipo',
            field=models.CharField(choices=[('espada', 'Espada'), ('machado', 'Machado'), ('arco', 'Arco'), ('foice', 'Foice'), ('lanca', 'Lança')], default='espada', max_length=10),
        ),
    ]
