# Generated by Django 5.0.7 on 2024-07-19 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arma', '0001_initial'),
        ('personagem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arma.arma')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personagem.personagem')),
            ],
        ),
    ]
